modLoader = "javafml"
loaderVersion = "[36,)"
license = "LGPLv3"

[[mods]]
modId = "connected"
version = "${version}"
displayName = "Connected"
displayURL="https://github.com/ThinkingStudios/Connected" #optional
# logoFile= "icon.png" #optional
credits="NuclearFarts" #optional
authors="TexTrue, ThinkingStudio" #optional
description = '''
Connected Block Textures unofficial Forge port.

Support for MCPatcher/Optifine-format connected textures.
'''

[[dependencies.connected]]
modId = "forge"
mandatory = true
versionRange = "[36,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.connected]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.connected]]
modId = "forgedapi"
mandatory = true
versionRange = "[0.1,]"
ordering = "NONE"
side = "BOTH"